<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PicklistsCountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run() 
    {
        DB::table('picklists_countries')->truncate();
        DB::table('picklists_countries')->insert(['name' => 'Afghanistan', 'code' => 'AF', 'nationality' => 'Afghan']);
        DB::table('picklists_countries')->insert(['name' => 'Albania', 'code' => 'AL', 'nationality' => 'Albanian']);
        DB::table('picklists_countries')->insert(['name' => 'Algeria', 'code' => 'DZ', 'nationality' => 'Algerian']);
        DB::table('picklists_countries')->insert(['name' => 'Andorra', 'code' => 'AD', 'nationality' => 'Catalan']);
        DB::table('picklists_countries')->insert(['name' => 'Angola', 'code' => 'AO', 'nationality' => 'Angolan']);
        DB::table('picklists_countries')->insert(['name' => 'Anguilla', 'code' => 'AI', 'nationality' => 'Anguillan']);
        DB::table('picklists_countries')->insert(['name' => 'Antarctica', 'code' => 'AQ', 'nationality' => 'Antarctican']);
        DB::table('picklists_countries')->insert(['name' => 'Argentina', 'code' => 'AR', 'nationality' => 'Argentinian']);
        DB::table('picklists_countries')->insert(['name' => 'Armenia', 'code' => 'AM', 'nationality' => 'Armenian']);
        DB::table('picklists_countries')->insert(['name' => 'Aruba', 'code' => 'AW', 'nationality' => 'Aruban']);
        DB::table('picklists_countries')->insert(['name' => 'Australia', 'code' => 'AU', 'nationality' => 'Australian']);
        DB::table('picklists_countries')->insert(['name' => 'Austria', 'code' => 'AT', 'nationality' => 'Austrian']);
        DB::table('picklists_countries')->insert(['name' => 'Azerbaijan', 'code' => 'AZ', 'nationality' => 'Azerbaijani']);
        DB::table('picklists_countries')->insert(['name' => 'Bahrain', 'code' => 'BH', 'nationality' => 'Bahraini']);
        DB::table('picklists_countries')->insert(['name' => 'Bangladesh', 'code' => 'BD', 'nationality' => 'Bangladeshi']);
        DB::table('picklists_countries')->insert(['name' => 'Belarus', 'code' => 'BY', 'nationality' => 'Belarusians']);
        DB::table('picklists_countries')->insert(['name' => 'Belgium', 'code' => 'BE', 'nationality' => 'Belgian']);
        DB::table('picklists_countries')->insert(['name' => 'Benin', 'code' => 'BJ', 'nationality' => 'Benin']);
        DB::table('picklists_countries')->insert(['name' => 'Bhutan', 'code' => 'BT', 'nationality' => 'Bhutani']);
        DB::table('picklists_countries')->insert(['name' => 'Bolivia', 'code' => 'BO', 'nationality' => 'Bolivian']);
        DB::table('picklists_countries')->insert(['name' => 'Bosnia', 'code' => 'BA', 'nationality' => 'Bosnian']);
        DB::table('picklists_countries')->insert(['name' => 'Botswana', 'code' => 'BW', 'nationality' => 'Batswana']);
        DB::table('picklists_countries')->insert(['name' => 'Brazil', 'code' => 'BR', 'nationality' => 'Brazilian']);
        DB::table('picklists_countries')->insert(['name' => 'Brunei', 'code' => 'BN', 'nationality' => 'Bruneian']);
        DB::table('picklists_countries')->insert(['name' => 'Bulgaria, Republic of', 'code' => 'BG', 'nationality' => 'Bulgarian']);
        DB::table('picklists_countries')->insert(['name' => 'Burkina Faso', 'code' => 'BF', 'nationality' => 'Burkinabé']);
        DB::table('picklists_countries')->insert(['name' => 'Burundi', 'code' => 'BI', 'nationality' => 'Burundian']);
        DB::table('picklists_countries')->insert(['name' => 'Cambodia', 'code' => 'KH', 'nationality' => 'Cambodian']);
        DB::table('picklists_countries')->insert(['name' => 'Cameroon', 'code' => 'CM', 'nationality' => 'Cameroonian']);
        DB::table('picklists_countries')->insert(['name' => 'Canada', 'code' => 'CA', 'nationality' => 'Canadian']);
        DB::table('picklists_countries')->insert(['name' => 'Cape Verde', 'code' => 'CV', 'nationality' => 'Creole']);
        DB::table('picklists_countries')->insert(['name' => 'Central African Republic', 'code' => 'CF', 'nationality' => 'Central African']);
        DB::table('picklists_countries')->insert(['name' => 'Chad', 'code' => 'TD', 'nationality' => 'Chad']);
        DB::table('picklists_countries')->insert(['name' => 'Chile', 'code' => 'CL', 'nationality' => 'Chilean']);
        DB::table('picklists_countries')->insert(['name' => 'China, People\'s Republic of', 'code' => 'CN', 'nationality' => 'Chinese']);
        DB::table('picklists_countries')->insert(['name' => 'Colombia', 'code' => 'CO', 'nationality' => 'Colombian']);
        DB::table('picklists_countries')->insert(['name' => 'Comoros', 'code' => 'KM', 'nationality' => 'Comorian']);
        DB::table('picklists_countries')->insert(['name' => 'Congo', 'code' => 'CG', 'nationality' => 'Kituba']);
        DB::table('picklists_countries')->insert(['name' => 'Costa Rica', 'code' => 'CR', 'nationality' => 'Costa Rican']);
        DB::table('picklists_countries')->insert(['name' => 'Croatia', 'code' => 'HR', 'nationality' => 'Croatian']);
        DB::table('picklists_countries')->insert(['name' => 'Cuba', 'code' => 'CU', 'nationality' => 'Cuban']);
        DB::table('picklists_countries')->insert(['name' => 'Curaçao', 'code' => 'CW', 'nationality' => 'Curaçao']);
        DB::table('picklists_countries')->insert(['name' => 'Cyprus', 'code' => 'CY', 'nationality' => 'Cypriot']);
        DB::table('picklists_countries')->insert(['name' => 'Czech Republic', 'code' => 'CZ', 'nationality' => 'Czech']);
        DB::table('picklists_countries')->insert(['name' => 'Denmark', 'code' => 'DK', 'nationality' => 'Danish']);
        DB::table('picklists_countries')->insert(['name' => 'Djibouti', 'code' => 'DJ', 'nationality' => 'Djiboutian']);
        DB::table('picklists_countries')->insert(['name' => 'Dominican Republic', 'code' => 'DO', 'nationality' => 'Dominican']);
        DB::table('picklists_countries')->insert(['name' => 'Ecuador', 'code' => 'EC', 'nationality' => 'Ecuadorian']);
        DB::table('picklists_countries')->insert(['name' => 'Egypt', 'code' => 'EG', 'nationality' => 'Egyptian']);
        DB::table('picklists_countries')->insert(['name' => 'El Salvador', 'code' => 'SV', 'nationality' => 'Salvadorian']);
        DB::table('picklists_countries')->insert(['name' => 'England', 'code' => 'EN', 'nationality' => 'English']);
        DB::table('picklists_countries')->insert(['name' => 'Estonia', 'code' => 'EE', 'nationality' => 'Estonian']);
        DB::table('picklists_countries')->insert(['name' => 'Eswatini', 'code' => 'SZ', 'nationality' => 'Swazi']);
        DB::table('picklists_countries')->insert(['name' => 'Ethiopia', 'code' => 'ET', 'nationality' => 'Ethiopian']);
        DB::table('picklists_countries')->insert(['name' => 'Faroe Islands', 'code' => 'FO', 'nationality' => 'Faroese']);
        DB::table('picklists_countries')->insert(['name' => 'Fiji', 'code' => 'FJ', 'nationality' => 'Fijian']);
        DB::table('picklists_countries')->insert(['name' => 'Finland', 'code' => 'FI', 'nationality' => 'Finnish']);
        DB::table('picklists_countries')->insert(['name' => 'France', 'code' => 'FR', 'nationality' => 'French']);
        DB::table('picklists_countries')->insert(['name' => 'Gabon', 'code' => 'GA', 'nationality' => 'Gabonese']);
        DB::table('picklists_countries')->insert(['name' => 'Gambia', 'code' => 'GM', 'nationality' => 'Gambian']);
        DB::table('picklists_countries')->insert(['name' => 'Georgia', 'code' => 'GE', 'nationality' => 'Georgia']);
        DB::table('picklists_countries')->insert(['name' => 'Germany', 'code' => 'DE', 'nationality' => 'German']);
        DB::table('picklists_countries')->insert(['name' => 'Ghana', 'code' => 'GH', 'nationality' => 'Ghanaian']);
        DB::table('picklists_countries')->insert(['name' => 'Gibraltar', 'code' => 'GI', 'nationality' => 'British']);
        DB::table('picklists_countries')->insert(['name' => 'Greece', 'code' => 'GR', 'nationality' => 'Greek']);
        DB::table('picklists_countries')->insert(['name' => 'Greenland', 'code' => 'GL', 'nationality' => 'Danish-Norwegian']);
        DB::table('picklists_countries')->insert(['name' => 'Grenada', 'code' => 'GD', 'nationality' => 'Grenadian']);
        DB::table('picklists_countries')->insert(['name' => 'Guadeloupe', 'code' => 'GP', 'nationality' => 'Guadeloupe']);
        DB::table('picklists_countries')->insert(['name' => 'Guam', 'code' => 'GU', 'nationality' => 'Guamanians']);
        DB::table('picklists_countries')->insert(['name' => 'Guatemala', 'code' => 'GT', 'nationality' => 'Guatemalan']);
        DB::table('picklists_countries')->insert(['name' => 'Guernsey', 'code' => 'GG', 'nationality' => 'Britannica']);
        DB::table('picklists_countries')->insert(['name' => 'Guinea', 'code' => 'GN', 'nationality' => 'Guinea']);
        DB::table('picklists_countries')->insert(['name' => 'Haiti', 'code' => 'HT', 'nationality' => 'Haitian']);
        DB::table('picklists_countries')->insert(['name' => 'Honduras', 'code' => 'HN', 'nationality' => 'Honduran']);
        DB::table('picklists_countries')->insert(['name' => 'Hong Kong', 'code' => 'HK', 'nationality' => 'Chinese']);
        DB::table('picklists_countries')->insert(['name' => 'Hungary', 'code' => 'HU', 'nationality' => 'Hungarian']);
        DB::table('picklists_countries')->insert(['name' => 'Iceland', 'code' => 'IS', 'nationality' => 'Icelandic']);
        DB::table('picklists_countries')->insert(['name' => 'India', 'code' => 'IN', 'nationality' => 'Indian']);
        DB::table('picklists_countries')->insert(['name' => 'Indonesia', 'code' => 'ID', 'nationality' => 'Indonesian']);
        DB::table('picklists_countries')->insert(['name' => 'Iran, Islamic Republic of', 'code' => 'IR', 'nationality' => 'Iranian']);
        DB::table('picklists_countries')->insert(['name' => 'Iraq', 'code' => 'IQ', 'nationality' => 'Iraqi']);
        DB::table('picklists_countries')->insert(['name' => 'Ireland', 'code' => 'IE', 'nationality' => 'Irish']);
        DB::table('picklists_countries')->insert(['name' => 'Isle of Man', 'code' => 'IM', 'nationality' => 'British']);
        DB::table('picklists_countries')->insert(['name' => 'Israel', 'code' => 'IL', 'nationality' => 'Israeli']);
        DB::table('picklists_countries')->insert(['name' => 'Italy', 'code' => 'IT', 'nationality' => 'Italian']);
        DB::table('picklists_countries')->insert(['name' => 'Jamaica', 'code' => 'JM', 'nationality' => 'Jamaican']);
        DB::table('picklists_countries')->insert(['name' => 'Japan', 'code' => 'JP', 'nationality' => 'Japanese']);
        DB::table('picklists_countries')->insert(['name' => 'Jordan', 'code' => 'JO', 'nationality' => 'Jordanian']);
        DB::table('picklists_countries')->insert(['name' => 'Kazakhstan', 'code' => 'KZ', 'nationality' => 'Kazakhstani']);
        DB::table('picklists_countries')->insert(['name' => 'Kenya', 'code' => 'KE', 'nationality' => 'Kenyan']);
        DB::table('picklists_countries')->insert(['name' => 'Kiribati', 'code' => 'KI', 'nationality' => 'Gilbertese']);
        DB::table('picklists_countries')->insert(['name' => 'Kiribati', 'code' => 'KP', 'nationality' => 'Korean']);
        DB::table('picklists_countries')->insert(['name' => 'Korea', 'code' => 'KP', 'nationality' => 'Korean']);
        DB::table('picklists_countries')->insert(['name' => 'Kuwait', 'code' => 'KW', 'nationality' => 'Kuwaiti']);
        DB::table('picklists_countries')->insert(['name' => 'Kyrgyzstan', 'code' => 'KG', 'nationality' => 'Kyrgyzstan']);
        DB::table('picklists_countries')->insert(['name' => 'Laos', 'code' => 'LA', 'nationality' => 'Lao']);
        DB::table('picklists_countries')->insert(['name' => 'Latvia', 'code' => 'LV', 'nationality' => 'Latvian']);
        DB::table('picklists_countries')->insert(['name' => 'Lebanon', 'code' => 'LB', 'nationality' => 'Lebanese']);
        DB::table('picklists_countries')->insert(['name' => 'Liberia', 'code' => 'LR', 'nationality' => 'Liberian']);
        DB::table('picklists_countries')->insert(['name' => 'Libya', 'code' => 'LI', 'nationality' => 'Libyan']);
        DB::table('picklists_countries')->insert(['name' => 'Liechtenstein', 'code' => 'LI', 'nationality' => 'Liechtensteiners']);
        DB::table('picklists_countries')->insert(['name' => 'Lithuania', 'code' => 'LT', 'nationality' => 'Lithuanian']);
        DB::table('picklists_countries')->insert(['name' => 'Luxembourg', 'code' => 'LU', 'nationality' => 'Luxembourg']);
        DB::table('picklists_countries')->insert(['name' => 'Macao', 'code' => 'MO', 'nationality' => 'Chinese']);
        DB::table('picklists_countries')->insert(['name' => 'Madagascar', 'code' => 'MG', 'nationality' => 'Malagasy']);
        DB::table('picklists_countries')->insert(['name' => 'Malawi', 'code' => 'MW', 'nationality' => 'Malawi']);
        DB::table('picklists_countries')->insert(['name' => 'Malaysia', 'code' => 'MY', 'nationality' => 'Malaysian']);
        DB::table('picklists_countries')->insert(['name' => 'Maldives', 'code' => 'MV', 'nationality' => 'Maldivian ']);
        DB::table('picklists_countries')->insert(['name' => 'Mali', 'code' => 'ML', 'nationality' => 'Malian']);
        DB::table('picklists_countries')->insert(['name' => 'Malta', 'code' => 'MT', 'nationality' => 'Maltese']);
        DB::table('picklists_countries')->insert(['name' => 'Marshall Islands', 'code' => 'MH', 'nationality' => 'Marshallese']);
        DB::table('picklists_countries')->insert(['name' => 'Martinique', 'code' => 'MQ', 'nationality' => 'Martinique']);
        DB::table('picklists_countries')->insert(['name' => 'Mauritania', 'code' => 'MR', 'nationality' => 'Mauritanian']);
        DB::table('picklists_countries')->insert(['name' => 'Mauritius', 'code' => 'MU', 'nationality' => 'Mauritians']);
        DB::table('picklists_countries')->insert(['name' => 'Mayotte', 'code' => 'YT', 'nationality' => 'Mayotte']);
        DB::table('picklists_countries')->insert(['name' => 'Mexico', 'code' => 'MX', 'nationality' => 'Mexican']);
        DB::table('picklists_countries')->insert(['name' => 'Micronesia', 'code' => 'FM', 'nationality' => 'Micronesian']);
        DB::table('picklists_countries')->insert(['name' => 'Moldova', 'code' => 'MD', 'nationality' => 'Moldovan']);
        DB::table('picklists_countries')->insert(['name' => 'Monaco', 'code' => 'MC', 'nationality' => 'Monégasque']);
        DB::table('picklists_countries')->insert(['name' => 'Mongolia', 'code' => 'MN', 'nationality' => 'Mongolian']);
        DB::table('picklists_countries')->insert(['name' => 'Montenegro', 'code' => 'ME', 'nationality' => 'Montenegro']);
        DB::table('picklists_countries')->insert(['name' => 'Montserrat', 'code' => 'MS', 'nationality' => 'Montserrat']);
        DB::table('picklists_countries')->insert(['name' => 'Morocco', 'code' => 'MA', 'nationality' => 'Moroccan']);
        DB::table('picklists_countries')->insert(['name' => 'Mozambique', 'code' => 'MZ', 'nationality' => 'Mozambican']);
        DB::table('picklists_countries')->insert(['name' => 'Myanmar', 'code' => 'MM', 'nationality' => 'Burmese']);
        DB::table('picklists_countries')->insert(['name' => 'Namibia', 'code' => 'NA', 'nationality' => 'Namibian']);
        DB::table('picklists_countries')->insert(['name' => 'Nauru', 'code' => 'NR', 'nationality' => 'Nauruan']);
        DB::table('picklists_countries')->insert(['name' => 'Nepal', 'code' => 'NP', 'nationality' => 'Nepalese']);
        DB::table('picklists_countries')->insert(['name' => 'Netherlands', 'code' => 'NL', 'nationality' => 'Dutch']);
        DB::table('picklists_countries')->insert(['name' => 'Netherlands Antilles', 'code' => 'AN', 'nationality' => 'Netherlands Antilles']);
        DB::table('picklists_countries')->insert(['name' => 'New Caledonia', 'code' => 'NC', 'nationality' => 'Caledonian']);
        DB::table('picklists_countries')->insert(['name' => 'New Zealand', 'code' => 'NZ', 'nationality' => 'New Zealand']);
        DB::table('picklists_countries')->insert(['name' => 'Nicaragua', 'code' => 'NI', 'nationality' => 'Nicaraguan']);
        DB::table('picklists_countries')->insert(['name' => 'Nigeria', 'code' => 'NG', 'nationality' => 'Nigerian']);
        DB::table('picklists_countries')->insert(['name' => 'Niue', 'code' => 'NU', 'nationality' => 'Niuean']);
        DB::table('picklists_countries')->insert(['name' => 'Norfolk Island', 'code' => 'NF', 'nationality' => 'Norfolk Islanders']);
        DB::table('picklists_countries')->insert(['name' => 'Norway', 'code' => 'NO', 'nationality' => 'Norwegian']);
        DB::table('picklists_countries')->insert(['name' => 'Oman', 'code' => 'OM', 'nationality' => 'Omani']);
        DB::table('picklists_countries')->insert(['name' => 'Pakistan', 'code' => 'PK', 'nationality' => 'Pakistani']);
        DB::table('picklists_countries')->insert(['name' => 'Palau', 'code' => 'PW', 'nationality' => 'Palauan']);
        DB::table('picklists_countries')->insert(['name' => 'Palestinian Territory', 'code' => 'PS', 'nationality' => 'Palestine']);
        DB::table('picklists_countries')->insert(['name' => 'Panama', 'code' => 'PA', 'nationality' => 'Panamanian']);
        DB::table('picklists_countries')->insert(['name' => 'Papua New Guinea', 'code' => 'PG', 'nationality' => 'Papuan']);
        DB::table('picklists_countries')->insert(['name' => 'Paraguay', 'code' => 'PY', 'nationality' => 'Paraguayan']);
        DB::table('picklists_countries')->insert(['name' => 'Peru', 'code' => 'PE', 'nationality' => 'Peruvian']);
        DB::table('picklists_countries')->insert(['name' => 'Philippines', 'code' => 'PH', 'nationality' => 'Filipino']);
        DB::table('picklists_countries')->insert(['name' => 'Poland', 'code' => 'PL', 'nationality' => 'Polish']);
        DB::table('picklists_countries')->insert(['name' => 'Portugal', 'code' => 'PT', 'nationality' => 'Portuguese']);
        DB::table('picklists_countries')->insert(['name' => 'Puerto Rico', 'code' => 'PR', 'nationality' => 'Puerto Rican']);
        DB::table('picklists_countries')->insert(['name' => 'Qatar', 'code' => 'QA', 'nationality' => 'Qatari']);
        DB::table('picklists_countries')->insert(['name' => 'Republic of North Macedonia', 'code' => 'MK', 'nationality' => 'Macedonian']);
        DB::table('picklists_countries')->insert(['name' => 'Romania', 'code' => 'RO', 'nationality' => 'Romanian']);
        DB::table('picklists_countries')->insert(['name' => 'Russian', 'code' => 'RU', 'nationality' => 'Russian']);
        DB::table('picklists_countries')->insert(['name' => 'Rwanda', 'code' => 'RW', 'nationality' => 'Rwandan']);
        DB::table('picklists_countries')->insert(['name' => 'Samoa', 'code' => 'WS', 'nationality' => 'Samoan']);
        DB::table('picklists_countries')->insert(['name' => 'San Marino', 'code' => 'SM', 'nationality' => 'Italian']);
        DB::table('picklists_countries')->insert(['name' => 'Sao Tome and Principe', 'code' => 'ST', 'nationality' => 'Portuguese']);
        DB::table('picklists_countries')->insert(['name' => 'Saudi Arabia', 'code' => 'SA', 'nationality' => 'Saudi']);
        DB::table('picklists_countries')->insert(['name' => 'Scotland', 'code' => 'SCT', 'nationality' => 'Scottish']);
        DB::table('picklists_countries')->insert(['name' => 'Senegal', 'code' => 'SN', 'nationality' => 'Senegalese']);
        DB::table('picklists_countries')->insert(['name' => 'Serbia', 'code' => 'RS', 'nationality' => 'Serbian']);
        DB::table('picklists_countries')->insert(['name' => 'Seychelles', 'code' => 'SC', 'nationality' => 'Seychellois Creole']);
        DB::table('picklists_countries')->insert(['name' => 'Sierra Leone', 'code' => 'SL', 'nationality' => 'Sierra Leonean']);
        DB::table('picklists_countries')->insert(['name' => 'Singapore', 'code' => 'SG', 'nationality' => 'Singaporean']);
        DB::table('picklists_countries')->insert(['name' => 'Slovakia', 'code' => 'SK', 'nationality' => 'Slovak']);
        DB::table('picklists_countries')->insert(['name' => 'Slovenia', 'code' => 'SI', 'nationality' => 'Slovenian']);
        DB::table('picklists_countries')->insert(['name' => 'Solomon Islands', 'code' => 'SB', 'nationality' => 'Melanesian']);
        DB::table('picklists_countries')->insert(['name' => 'Somalia', 'code' => 'SO', 'nationality' => 'Somalian']);
        DB::table('picklists_countries')->insert(['name' => 'South Africa', 'code' => 'ZA', 'nationality' => 'South African']);
        DB::table('picklists_countries')->insert(['name' => 'South Korea', 'code' => 'KR', 'nationality' => 'Korean']);
        DB::table('picklists_countries')->insert(['name' => 'Spain', 'code' => 'ES', 'nationality' => 'Spainish']);
        DB::table('picklists_countries')->insert(['name' => 'Sri Lanka', 'code' => 'LK', 'nationality' => 'Sri Lankan']);
        DB::table('picklists_countries')->insert(['name' => 'Sudan', 'code' => 'SD', 'nationality' => 'Sudanese']);
        DB::table('picklists_countries')->insert(['name' => 'Sweden', 'code' => 'SE', 'nationality' => 'Swedish']);
        DB::table('picklists_countries')->insert(['name' => 'Switzerland', 'code' => 'CH', 'nationality' => 'Swedish']);
        DB::table('picklists_countries')->insert(['name' => 'Syria', 'code' => 'SY', 'nationality' => 'Syrian']);
        DB::table('picklists_countries')->insert(['name' => 'Taiwan', 'code' => 'TW', 'nationality' => 'Taiwanese']);
        DB::table('picklists_countries')->insert(['name' => 'Tajikistan', 'code' => 'TJ', 'nationality' => 'Tajikistani']);
        DB::table('picklists_countries')->insert(['name' => 'Tanzania', 'code' => 'TZ', 'nationality' => 'Tanzanian']);
        DB::table('picklists_countries')->insert(['name' => 'Thailand', 'code' => 'TH', 'nationality' => 'Thai']);
        DB::table('picklists_countries')->insert(['name' => 'Timor-Leste', 'code' => 'TL', 'nationality' => 'Timorese']);
        DB::table('picklists_countries')->insert(['name' => 'Togo', 'code' => 'TG', 'nationality' => 'Tongan']);
        DB::table('picklists_countries')->insert(['name' => 'Tokelau', 'code' => 'TK', 'nationality' => 'Tokelauans']);
        DB::table('picklists_countries')->insert(['name' => 'Tonga, Kingdom of', 'code' => 'TO', 'nationality' => 'Tongan']);
        DB::table('picklists_countries')->insert(['name' => 'Tunisia', 'code' => 'TN', 'nationality' => 'Tunisian']);
        DB::table('picklists_countries')->insert(['name' => 'Turkey', 'code' => 'TR', 'nationality' => 'Turkish']);
        DB::table('picklists_countries')->insert(['name' => 'Turkmenistan', 'code' => 'TM', 'nationality' => 'Turkmen']);
        DB::table('picklists_countries')->insert(['name' => 'Uganda', 'code' => 'UG', 'nationality' => 'Ugandan']);
        DB::table('picklists_countries')->insert(['name' => 'Ukraine', 'code' => 'UA', 'nationality' => 'Ukrainian']);
        DB::table('picklists_countries')->insert(['name' => 'United Arab Emirates', 'code' => 'AE', 'nationality' => 'Emirati']);
        DB::table('picklists_countries')->insert(['name' => 'United Kingdom', 'code' => 'GB', 'nationality' => 'British']);
        DB::table('picklists_countries')->insert(['name' => 'United States of America', 'code' => 'US', 'nationality' => 'American ']);
        DB::table('picklists_countries')->insert(['name' => 'Uruguay', 'code' => 'VI', 'nationality' => 'Uruguayan']);
        DB::table('picklists_countries')->insert(['name' => 'Uzbekistan', 'code' => 'UZ', 'nationality' => 'Uzbek']);
        DB::table('picklists_countries')->insert(['name' => 'Vanuatu', 'code' => 'VU', 'nationality' => 'Ni-Vanuatu']);
        DB::table('picklists_countries')->insert(['name' => 'Venezuela', 'code' => 'VE', 'nationality' => 'Venezuelan']);
        DB::table('picklists_countries')->insert(['name' => 'Vietnam', 'code' => 'VN', 'nationality' => 'Vietnamese']);
        DB::table('picklists_countries')->insert(['name' => 'Wales', 'code' => 'WLS', 'nationality' => 'Welsh']);
        DB::table('picklists_countries')->insert(['name' => 'Western Sahara', 'code' => 'EH', 'nationality' => 'Saharan']);
        DB::table('picklists_countries')->insert(['name' => 'Yemen', 'code' => 'YE', 'nationality' => ' Yemeni']);
        DB::table('picklists_countries')->insert(['name' => 'Zambia', 'code' => 'ZM', 'nationality' => 'Zambian']);
        DB::table('picklists_countries')->insert(['name' => 'Zimbabwe', 'code' => 'ZW', 'nationality' => 'Zimbabwean']);

    }
}
